### ISSUE TITLE
Cocoapods: Unable to find specifications for this `EasyPeasy`

### ISSUE THREAD

**Issue by otymartin** [nakiostudio/EasyPeasy#15]
i can't `pod install` this for god knows what reason.

Every other pod installs but this.

**Comment by khose** [comment]
Hi @otymartin . Could you please paste your `Podfile `here or send it to @nakiostudio . 
EasyPeasy is correctly published in Cocoapods specs repo, so looks like a configuration problem.

Thanks!

**Comment by nakiostudio** [comment]
Hi @otymartin 👋, as @khose mentioned EasyPeasy is correctly published, maybe your problem is related with a known issue updating the CocoaPods specs [more info here](https://github.com/CocoaPods/CocoaPods/issues/4989) or the iOS platform set in your Podfile is lower than iOS 8.0.

**Comment by otymartin** [comment]
@khose @nakiostudio Thanks for the response. here is my podfile
```swift
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Ballout' do
pod 'Parse'
pod 'ParseLiveQuery'
pod 'Stripe'
pod 'SwiftyButton'
pod 'ChameleonFramework'
pod 'EasyPeasy'
end
```

**Comment by nakiostudio** [comment]
Thanks @otymartin, everything looks fine. Could you try clearing the CocoaPods cache and running `pod install` again?

```bash
$ rm -rf "${HOME}/Library/Caches/CocoaPods"
$ pod install
```

**Comment by otymartin** [comment]
@nakiostudio what is `{HOME}`? Im no too familiar with directories for cocoapods

**Comment by nakiostudio** [comment]
Hi @otymartin. `{HOME}` is the path to your home directory. You can easily get it with the command:
```bash
echo $HOME
```

**Comment by otymartin** [comment]
@nakiostudio I've tried so afew times and no luck.
```swift
rm -rf "/Users/otymartin/Library/Caches/CocoaPods"
```

**Comment by nakiostudio** [comment]
Try `rm -rf /Users/otymartin/Library/Caches/CocoaPods` without the double quotes 👍

**Comment by otymartin** [comment]
@nakiostudio issue persists. Is it supposed to do something when I run that command? Because once i press enter it nothing happens. im just taken to the next command line with the blinking cursor

**Comment by nakiostudio** [comment]
After doing that you have to run `pod install` again. That command simply removes the CocoaPods caches.

**Comment by otymartin** [comment]
No luck. the issue persists.

**Comment by nakiostudio** [comment]
Sorry to hear that 😞 , in that case I recommend you to open an issue in the CocoaPods repo https://github.com/CocoaPods/CocoaPods

**Comment by otymartin** [comment]
@nakiostudio apparently im the only one with the problem ;(  I'll keep digging and update when I find a solution

Thanks for your help

**Comment by Andrej123** [comment]
@otymartin no, you're not the only one with this issue. I've managed to solve it by running 
`pod repo update` and then `pod install`

**Comment by nakiostudio** [comment]
As @Andrej123 pointed out, this is a CocoaPods issue that should be fixed by running `pod repo update` 👍

**Comment by sierramclawhorn** [comment]
I have this same issue, but no luck after running` pod repo update`
