### ISSUE TITLE
Can you combine multiple modifiers?

### ISSUE THREAD

**Issue by avalanched** [nakiostudio/EasyPeasy#17]
my view has a need for a minimum width of 37, but always multiplied by 1.5
```
countLabel <- [
    Width(>=37),
    Width(*1.5)
]
```

it does not generate an error, but it doesn't work either..

**Comment by nakiostudio** [comment]
Hi @avalanched 👋
I'm afraid you are not allowed to do that for now. In that piece of code `Width(*1.5)` will override `Width(>=37)`. Instead you can set different priorities for those Attributes (if that's the intended implementation).

Thanks for the issue 👍

**Comment by avalanched** [comment]
that also means you cannot constraint the following:

> view should have a width of equal or greater then 200 but no greater then 400

**Comment by nakiostudio** [comment]
You can constrain it like this:

```swift
view <- [
    Width(<=400),
    Width(>=200).with(.MediumPriority)
]
```

**Comment by avalanched** [comment]
👍  thanks
