### ISSUE TITLE
Using Size Classes and Orientation in EasyPeasy

### ISSUE THREAD

**Issue by r-a-o** [nakiostudio/EasyPeasy#18]
How do I use Size Classes while writing constraints for my elements for different device screen resolutions and orientations?
Ex:
I want to position elements in a certain way when device is in Portrait mode and position them very differently when it enters Landscape mode.

Do I have to use `traitCollection` to do this?

**Comment by nakiostudio** [comment]
Hi @r-a-o 👋 

You can do it using [Conditions](https://github.com/nakiostudio/EasyPeasy#conditions). The example below shows you how to set a different width constraint depending on orientation:

```swift
view <- [
    Width(120).when { UIDeviceOrientationIsPortrait(UIDevice.currentDevice().orientation) },
    Width(200).when { UIDeviceOrientationIsLandscape(UIDevice.currentDevice().orientation) }
]
```

Then, when the orientation changes, you just need to call `view.easy_reload()` to reload the constraints. You can do it using `UITraitCollections` too.

**Comment by r-a-o** [comment]
Hi 👋  

Thanks! Got this to work after calling `view.easy_reload()` from UIDeviceOrientationDidChangeNotification observer.

Now, there is another issue. The Portrait condition is never getting applied! 
ie.,
`Width(120).when { UIDeviceOrientationIsPortrait(UIDevice.currentDevice().orientation) }`

But when the device orientation changes to Landscape, the landscape condition is getting applied as expected. 

I guess this is because when the app loads my screen, `UIDeviceOrientationIsPortrait(UIDevice.currentDevice().orientation)` and `UIDeviceOrientationIsLandscape(UIDevice.currentDevice().orientation)` both are `false` for some reason.

Also, how do I apply size classes in my conditions?

**Comment by nakiostudio** [comment]
With size classes it would be similar to this:

```swift

view <- [
    Width(120).when { [weak view] in
        return view?.traitCollection.horizontalSizeClass == .Compact
    },
    
    Width(200).when { [weak view] in
        return view?.traitCollection.horizontalSizeClass == .Regular
    }
]
```

Again you can always find the way to simplify and reuse this extending `UIView`, and don't forget to call `view.easy_reload()` when the trait collection changes :)

**Comment by r-a-o** [comment]
Thanks. 
I was expecting the views which have conditional constraints which involve either orientation change or size classes to call easy_reload() smartly on their own. ;) 

I think constraints which involve Size classes and device Orientation deserve a method of their own just like Width, Top etc., rather than letting user do it in the Condition block. But that's just me. :)

**Comment by nakiostudio** [comment]
It'd be handy for sure. I'll consider implementing it 👍

**Comment by HumidBrains** [comment]
Hi @nakiostudio 
I see this issue is closed, but can you please help me out with a complete example of how you use size classes? I've read the above, but I just can't seem to get the hang of it.

Thanks!

**Comment by nakiostudio** [comment]
Hi @HumidBrains :wave: Sure thing, for some reason I missed your message, sorry for the late answer. 

The example below shows a controller with a label positioned 20px to the top of the screen, with height 60px and 0px margins to left and right of the view containing the label (in this case the controller's view). This applies only for a **compact** horizontal size class whereas for a **regular** horizontal size class the desired implementation is a label with a width of 400px, height 60px and centered horizontal and vertically:

```swift
import UIKit
import EasyPeasy

class ViewController: UIViewController {
    
    private let label: UILabel = {
        let label = UILabel(frame: CGRectZero)
        label.textColor = UIColor.blueColor()
        label.text = "My string"
        return label
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Add label to controller's view
        self.view.addSubview(self.label)
        
        // Setup constraints applying to compact horizontal size class
        self.label <- [
            Top(20), Left(0), Right(0), Height(60)
        ].when { [weak self] in
            self?.label.traitCollection.horizontalSizeClass == .Compact
        }
        
        // Setup constraints applying to regular horizontal size class
        self.label <- [
            Center(0), Width(400), Height(60)
        ].when { [weak self] in
            self?.label.traitCollection.horizontalSizeClass == .Regular
        }
    }
    
    override func traitCollectionDidChange(previousTraitCollection: UITraitCollection?) {
        super.traitCollectionDidChange(previousTraitCollection)
        
        // Reload EasyPeasy constraints when traitCollection changes
        self.label.easy_reload()
    }
    
}
``` 

Please let me know if the example doesn't help with your doubts!

**Comment by HumidBrains** [comment]
Hi @nakiostudio, I'm so sorry for slow response, thank you for your detailed answer.

I get size classes to work, but I'm still not friends with easy_reload(). For example, in a table view where you may have the same view (say a speech bubble in a chat app) alternating between left and right side of the screen depending on if messages are incoming or outgoing. How do you update the constraints for dequeued cells that are reused? I found that I end up with no active constraints at all as soon as cells are reused.

Thanks for all your help.

**Comment by ashfurrow** [comment]
This solution makes sense, we should consider adding it to the examples in the Readme, too. This issue is the only place I could find discussing size classes. I can submit a PR if it would be helpful.

**Comment by nakiostudio** [comment]
Hi @ashfurrow 👋 

If you have the time please feel free to do it :) if not I can add it right after completing #29 

For instance, this is how I deal with size classes in a personal project:

```swift
func Traits() -> UITraitCollection? {
    return UIApplication.sharedApplication().keyWindow?.traitCollection
}

func HorizontalSizeClass() -> UIUserInterfaceSizeClass? {
    return Traits()?.horizontalSizeClass
}

func VerticalSizeClass() -> UIUserInterfaceSizeClass? {
    return Traits()?.verticalSizeClass
}
```

```swift
myView <- [
   Size(20).when { HorizontalSizeClass() == .Compact },
   Size(40).when { HorizontalSizeClass() == .Regular },
]
```

In addition I was planning the creation of a *subspec* including some helpers easing size classes handling or what @phatmann suggested in #20.

**Comment by ashfurrow** [comment]
Cool, I'll see what I can do. Not sure if using the keywindow is always a good idea, for example in a split view or in a popover. Would using the self.ciew trait collection work for you?

**Comment by nakiostudio** [comment]
Yeah, the `.when { HorizontalSizeClass() == .Compact }` solution will only work when the controller bounds match the window ones. For all the other cases, I guess accessing the controller's view is the only way.

Thank you @ashfurrow !
