### ISSUE TITLE
How to pin to view controller top / bottom layout guides?

### ISSUE THREAD

**Issue by akaralar** [nakiostudio/EasyPeasy#21]
I'm trying to pin a view in a view controller to the bottom of the navigation bar with
`view <- Top().to(self.topLayoutGuide, .Bottom)`

but I get errors. I tried a few other ways to do this but I couldn't make the errors go away. Is there a way to pin to top and bottom layout guides of `UIViewController`?

I tried
`view <- Top().to(self.topLayoutGuide)`
`view <- Top().to(self.topLayoutGuide.bottomAnchor)`

**Comment by kamil-tomaszewski** [comment]
I was just about to write the same thing. `topLayoutGuide` is a `UILayoutSupport` class, so this is a bit confusing. EasyPeasy is expecting `UILayoutGuide` which makes sense for custom layout guides.

**Comment by nakiostudio** [comment]
Hi @akaralar and @kamil-tomaszewski 👋 

As @kamil-tomaszewski said EasyPeasy only works with custom guides but adding support to `UILayoutSupport` is quite trivial, I will release a version today implementing it 👍

**Comment by nakiostudio** [comment]
I've just merged #22 that creates the version 0.2.5 including this change. The [CHANGELOG](https://github.com/nakiostudio/EasyPeasy/blob/master/CHANGELOG.md) contains a quick example of use. 

@akaralar please close the issue if you are happy with the implementation.

**Comment by kamil-tomaszewski** [comment]
<3

**Comment by kamil-tomaszewski** [comment]
❤️

**Comment by akaralar** [comment]
I'll try it out in a few hours and update the issue. Thanks for the quick reply & implementation!

**Comment by nakiostudio** [comment]
I can confirm this is working fine, closing the issue :)
