### ISSUE TITLE
Unable to stick label to right

### ISSUE THREAD

**Issue by r-a-o** [nakiostudio/EasyPeasy#24]
I am able to stick my first label to left of my scrollView, but unable to stick second label to the right. Am I doing anything wrong here?

```
// SCROLL VIEW
    private lazy var scrollView: UIScrollView = {
        let scrollView = UIScrollView(frame: CGRectZero)
        return scrollView
    }()

override func viewDidLoad() {
        super.viewDidLoad()

        self.view.addSubview(self.scrollView)
        self.scrollView <- [
            Edges(UIEdgeInsetsMake(0, 0, 0, 0))
        ]
// LABEL 1 - works!
        let weeklyLabel = UILabel()
        weeklyLabel.text = "Weekly"
        self.scrollView.addSubview(weeklyLabel)
        weeklyLabel <- [
            Top(10).to(scrollView),
            Left(10)
        ]
// LABEL 2 - doesn't appear at all!
        let rateLabel = UILabel()
        self.scrollView.addSubview(rateLabel)
        rateLabel.text = "$4"
        rateLabel <- [
            Top(10).to(scrollView),
            Right(10)
        ]
}
```

**Comment by nakiostudio** [comment]
Hi @r-a-o :wave: 

I think your problem is not related with EasyPeasy. Have you set the 'contentSize' of your scrollview?

**Comment by r-a-o** [comment]
Tried by setting contentSize as well, didnt work. 
It shows all other elements which are sticking to left of the scrollView (even those outside scrollView) but the only element(second label in above code) that I am trying to make it stick to right is not appearing at all.

**Comment by r-a-o** [comment]
If I just replace `Right(10)` with `Left(10)` in second label positioning, it appears to the left as expected.

**Comment by r-a-o** [comment]
I have simplified the above code, could you give it a try? (with latest version of easypeasy)

**Comment by nakiostudio** [comment]
I don't have access to a computer right now but I will give it a try as soon as I can. However I think you need a UIView wrapping the content you want to add to the UIScrollView :+1:

**Comment by r-a-o** [comment]
Thanks. 
Tried introducing a UIView as a wrapper, still getting the same result. Everything appears except for the label which is positioned to the right. I'll try removing the scrollView altogether and see.

**Comment by r-a-o** [comment]
If I remove the scrollView and add elements to my UIView, it works fine.

**Comment by nakiostudio** [comment]
Applying constraints to views withing a scrollview is always tricky. Check this:

’’’
view.addSubview(scrollview)
scrollview <- Edges(0)

let contentView = UIView()
scrollview.addSubview(contentView)
contentView <- [
   Top(), Left(), Right(), Height(>=0)
]

let labelA = UILabel()
labelA.text = "foo"
contentView.addSubview(labelA)
labelA <- [
    Top(), Left(), Size(>=0)
]

let labelB = UILabel()
labelB.text = "bar"
contentView.addSubview(labelB)
labelB <- [
    Top(), Right(), Size(>=0)
]
’’’

**Comment by r-a-o** [comment]
Same! 
`Foo` appears to the left, `Bar` doesn't appear.

**Comment by nakiostudio** [comment]
And with this?

contentView <- [
Top(), Left(), Width().like(scrollview), Height(>=0)
]

**Comment by r-a-o** [comment]
Now its coming properly!

**Comment by nakiostudio** [comment]
Awesome! :D

**Comment by r-a-o** [comment]
Thanks a lot! 👍  
Prior to this I tried with Edges(0) and it didn't work and I gave up! :D 
Why didn't Edges(0) work? 
And does Right() require Width() to be defined?

**Comment by Kimberleyrene** [comment]
Stop sending me emaulkd

On July 2, 2016, at 17:54, Carlos Vidal <notifications@github.com> wrote:

Applying constraints to views withing a scrollview is always tricky. Check this:

’’’
view.addSubview(scrollview)
scrollview <- Edges(0)

let contentView = UIView()
scrollview.addSubview(contentView)
contentView <- [
   Top(), Left(), Right(), Height(>=0)
]

let labelA = UILabel()
labelA.text = "foo"
contentView.addSubview(labelA)
labelA <- [
    Top(), Left(), Size(>=0)
]

let labelB = UILabel()
labelB.text = "bar"
contentView.addSubview(labelB)
labelB <- [
    Top(), Right(), Size(>=0)
]
’’’

---
