### ISSUE TITLE
Is there any way to add width/height constraints to a view without adding it as a subview?

### ISSUE THREAD

**Issue by JohnEstropia** [nakiostudio/EasyPeasy#36]
Adding constant width and height constraints in nib/storyboard adds them directly to the view and not the superview.

I may have just missed it, but is there any way to keep this behavior in EasyPeasy?

**Comment by nakiostudio** [comment]
Hi @JohnEstropia :wave: 

As far as I remember that's what EasyPeasy does, but I may have missed something after the refactor I did for the version 1.0.0

**Comment by nakiostudio** [comment]
There are several tests, like [this one](https://github.com/nakiostudio/EasyPeasy/blob/master/Example/Tests/UIView%2BEasyTests.swift#L116) that confirm this behaviour. But again, it's 7am here and I may have missed something :sleeping:

**Comment by JohnEstropia** [comment]
@nakiostudio Thanks for the response. You're right, EasyPeasy already does this and I misunderstood the behavior.

The reason I thought otherwise is because there is currently no way to add the constraints before the view is added to any superview. So I guess my question is, is there any way to add constraints to a view without adding it as a subview? (for self-sizing views for example)

**Comment by nakiostudio** [comment]
Hi again @JohnEstropia !
The reason why the library doesn't allow that it's because it may lead to unexpected results. For your particular case, I would apply the attributes within the self-sizing view `didMoveToSuperview()` method.

**Comment by JohnEstropia** [comment]
I changed the issue title so as not to mislead other users.

Anyway I don't think the current implementation is missing anything, but with EasyPeasy is there any unwanted effect that may happen if the width/height constraint is added before a view is added to a superview? If there aren't any, is there an advantage to making them dependent on the superview via `didMoveToSuperview()`?

To clarify, I'm only talking about width/height constant attributes (i.e. constraints that aren't dependent on the superview)

**Comment by nakiostudio** [comment]
Hi again 👋 

For some reason I thought that I replied to your last message, sorry about that 😓

You are right, it's not worthwhile to avoid that for the sake of consistency. I will merge #38 giving support to your request 👍

**Comment by JohnEstropia** [comment]
Thanks!

**Comment by nakiostudio** [comment]
It's out! 🎉
