### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by phatmann** [nakiostudio/EasyPeasy#40]
Xcode 8 is out! Time to merge swift-3 branch.

**Comment by nakiostudio** [comment]
Hi @phatmann 👋 

I'm working on it! I will make a Swift 2.3 release and right after that one a Swift 3 version 💃

**Comment by nakiostudio** [comment]
Hi again 👋 

EasyPeasy 1.3 is out with Swift 2.3 support, now let's release 1.4 supporting Swift 3 :)

**Comment by dlosuna** [comment]
Looking forward to 1.4 version 👍

**Comment by nakiostudio** [comment]
Done 🎉 Sorry for the delay!
