### ISSUE TITLE
operator '<-' is unused warning

### ISSUE THREAD

**Issue by frytaz** [nakiostudio/EasyPeasy#44]
Keep seeing this warning in Swift 3:
Result of operator '<-' is unused

**Comment by nakiostudio** [comment]
Hi @frytaz 👋 

Sorry for the delay in my response. I cannot reproduce the issue and I'm quite surprised as I'm using the `@discardableResult` decorator. Could you please paste a code snippet here?

Thanks!

**Comment by frytaz** [comment]
Sorry it was my Xcode tried to convert EasyPeasy to new Swift syntax and messed it up

**Comment by nakiostudio** [comment]
Thanks for the update! 👍
