### ISSUE TITLE
Content hugging and content compression resistance priorities

### ISSUE THREAD

**Issue by ServusJon** [nakiostudio/EasyPeasy#47]
Hey, how can I use Content hugging and content compression resistance priorities with Easy Peasy?

**Comment by nakiostudio** [comment]
Hi @ServusJon 👋 

You can use content hugging and compression resistance priorities as usual, the only thing to keep in mind is that you need to play with the constraint priorities and to do so you would need to use the `.with` method when creating your attributes, more info [here](https://github.com/nakiostudio/EasyPeasy#priorities).

However, I use the following helper methods at work:

```swift
/**
    Content hugging & resistance helpers, because I'm tired of thinking about this
 */
extension UIView {
    
    /**
        Adjusts the view's size in order to wrap the content using as little space as possible when 
        wrap is true
        - parameter wrap: Whether the content should be wrapped
        - parameter axes: Axes affected by this rule
        - parameter priority: Priority of the constraint based in which the rule will take effect
     
        - returns the current `UIView` instance to ease the concatenation of operations
     */
    func easy_wrap(wrap: Bool, axes: [UILayoutConstraintAxis] = [.Vertical, .Horizontal], priority: Priority = .HighPriority, offset: Float = 10) -> UIView {
        for axis in axes {
            let value: Float = wrap ? priority.layoutPriority() + offset : priority.layoutPriority() - offset
            self.setContentHuggingPriority(value, forAxis: axis)
        }
        return self
    }
    
    /**
        Adjusts the view's size respecting or not the size of its content
        - parameter collapse: Whether the size of the content should preveal
        - parameter axes: Axes affected by this rule
        - parameter priority: Priority of the constraint based in which the rule will take effect
     
        - returns the current `UIView` instance to ease the concatenation of operations
     */
    func easy_collapse(collapse: Bool, axes: [UILayoutConstraintAxis] = [.Vertical, .Horizontal], priority: Priority = .HighPriority, offset: Float = 10) -> UIView {
        for axis in axes {
            let value: Float = collapse ? priority.layoutPriority() - offset : priority.layoutPriority() + offset
            self.setContentCompressionResistancePriority(value, forAxis: axis)
        }
        return self
    }
    
}
```

I don't find them particularly good reason why I haven't made them public until now.

This is an usage example:

```swift
private lazy var shippingLabel: UILabel = {
    let label = UILabel(frame: CGRectZero)
    label.easy_wrap(true, offset: 5).easy_collapse(false)
    return label
}()

I hope you find it helpful :)

**Comment by ServusJon** [comment]
Yes indeed. thank you. 

What would you use to achieve a layout that works in different orientations?

`    let image = UIView()

    override func viewDidLoad() {
        super.viewDidLoad()
        
        image.backgroundColor = .green
//        image.frame = CGRect(x: 10, y: 10, width: 200, height: 200)
        view.addSubview(image)


        image <- [
            Top(0).when { $0.isHorizontalRegular }, // portait
            Left(0),
            Right(0),
            Height(100)
        ]
        
        image <- [
            Top(100).when { $0.isVerticalCompact }, // landscape
            Height(10).when { $0.isVerticalCompact }, // portait
        ]
        
    }
    
    override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
        image.easy_reload()
    }`

The height of the view breaks when I go back to portrait after switching to landscape. I am struggling to structure the code in a way that it works for orientation and screensizes :-( 

Can you help?

**Comment by nakiostudio** [comment]
It's breaking because there is no `Height` attribute when the size class goes back to `HorizontalRegular`.

I think this should fix your code:

```swift
let image = UIView()

override func viewDidLoad() {
    super.viewDidLoad()
    view.addSubview(image)
    image <- [
        Top(0).when { $0.isHorizontalRegular }, // portait
        Left(0),
        Right(0),
        Height(100).when { $0.isHorizontalRegular }, // portait
    ]
    
    image <- [
        Top(100).when { $0.isVerticalCompact }, // landscape
        Height(10).when { $0.isVerticalCompact }, // portait
    ]
    
}

override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
    image.easy_reload()
}
```

**Comment by ServusJon** [comment]
Now the view is only visible in landscape. :-(  Is there a best practice to organize or setup constraints for a layout like this?

**Comment by nakiostudio** [comment]
You can structure it in many different ways, for example:

```swift
override func viewDidLoad() {
    super.viewDidLoad()
    view.addSubview(image)
    image <- [
        Top(0).when { $0.isHorizontalRegular },
        Height(100).when { $0.isHorizontalRegular },
        Top(100).when { $0.isVerticalCompact },
        Height(10).when { $0.isVerticalCompact },
        Left(0),
        Right(0),
    ]
   
}
```

or

```swift
override func viewDidLoad() {
    super.viewDidLoad()
    view.addSubview(image)

    // Common constraints
    image <- [
        Left(0),
        Right(0)
    ]

    // Horizontal regular
    image <- [
        Top(0),
        Height(100)
    ].when { $0.isHorizontalRegular }

    // Vertical compact
    image <- [ 
        Top(100),
        Height(10)
    ].when { $0.isVerticalCompact } 
}
```

But just to be clear, which frame would you like to have for landscape and portrait? I'm not sure what do you want to achieve.

**Comment by ServusJon** [comment]
This is just an example. In this example I want to change the height and top value based on orientation. In your examples the green block is still not visible in portrait.

**Comment by nakiostudio** [comment]
Ok, got it. Try with this :)

```swift
    image <- [
        Top(0).when { $0.isVerticalRegular },
        Height(100).when { $0.isVerticalRegular },
        Top(100).when { $0.isVerticalCompact },
        Height(10).when { $0.isVerticalCompact },
        Left(0),
        Right(0)
    ]
```

**Comment by ServusJon** [comment]
That works!

And what if I want to have a view a different width on an iPad depending on the Orientation? Size classes don't work here?

**Comment by nakiostudio** [comment]
Cool!

In that case you would need to figure it out in a different way as the size class will always be `Compact`. Remember that you can evaluate any condition within a `when` closure, like this:

```swift
Width(100.0).when {  [weak self] in
    return self?.isLandscape ?? false
}
```

**Comment by ServusJon** [comment]
not working :-( 
<img width="848" alt="bildschirmfoto 2016-12-21 um 14 07 32" src="https://cloud.githubusercontent.com/assets/783416/21390368/df10cd8e-c786-11e6-9be5-f8c64a8fdd05.png">

**Comment by nakiostudio** [comment]
Hey @ServusJon 👋 

I know I know, it was just an example showing how to check properties using `Conditions`. The property `isLandscape` is not part of `UIKit`, therefore you would need to implement it.

**Comment by ServusJon** [comment]
Thank you @nakiostudio that helped a lot. Sorry for all this noob questions…

**Comment by nakiostudio** [comment]
I don't think those are noob questions 🙂. Feel free to ask as much as you want or direct message me on [twitter](https://twitter.com/carlostify).

**Comment by edon2005** [comment]
HI,

How is it possible to use your wrap with new version ? :)
