### ISSUE TITLE
Center().to??

### ISSUE THREAD

**Issue by jazzgil** [nakiostudio/EasyPeasy#54]
The Readme starts with an example having a Center(0.0).to(red). However, the code doesn't seem to support it. i.e. no .to func in CompoundAttributes. Is this just an old typo in the readme?

Ended up doing [CenterX().to(red), CenterY().to(red)]...

**Comment by nakiostudio** [comment]
Hi @jazzgil 👋 thanks for reporting!

That's wrong indeed, position `CompoundAttributes` like `Center` and `Edges` do not implement the `.to` method. Your approach is the right one. 

Will update the README as soon as possible :+1:

**Comment by nakiostudio** [comment]
Updated!

**Comment by jazzgil** [comment]
Kinda hoped it's the other way around ;)
Anyway, thanks. Btw, you forgot a comma.

**Comment by nakiostudio** [comment]
I know it's not ideal but there are some implications implementing `.to`
for `CompoundAttributes`. I will think on a solution.

Yeah, I missed the comma. Last time I commit from the queue to board a
plane 😅.

**Comment by jazzgil** [comment]
:D

**Comment by nakiostudio** [comment]
Fixed missing comma >_<'

I will implement the `.to()` method for `CompoundAttributes` later this week 👍

**Comment by jazzgil** [comment]
You're a kickass, mr. EasyPeasy!
