### ISSUE TITLE
Cannot invoke initializer for type 'Height' with an argument list of type '(Int)'

### ISSUE THREAD

**Issue by r-a-o** [nakiostudio/EasyPeasy#58]
What is the proper way to pass an int/float/double variable to Height()/Width()/etc Attributes? 

I get the following error:

`Cannot invoke initializer for type 'Height' with an argument list of type '(Int)'`

**Comment by nakiostudio** [comment]
Hi @r-a-o 👋 

You need to cast those values to `CGFloat`. Like this:

```swift
let myInteger: Int = 10
Width(CGFloat(myInteger))
```

Hope it helps!

**Comment by r-a-o** [comment]
CGFloat works.

I tried Float, Double and gave up. 

Thanks.
