### ISSUE TITLE
Add safeAreaLayoutGuide to layout also on iPhone X

### ISSUE THREAD

**Issue by ServusJon** [nakiostudio/EasyPeasy#67]
More info: https://www.youtube.com/watch?v=FXDEaL3mcCo

**Comment by nakiostudio** [comment]
Hey @ServusJon 

Thanks for reporting, I will ship this as soon as possible 👍

**Comment by nakiostudio** [comment]
Hey @ServusJon 👋 

As safeAreaLayoutGuide is a `UILayoutGuide` the library already supports this therefore no changes are required :)

**Comment by ServusJon** [comment]
Can you please give me an example how I can use the safearealayoutguide on a view?
Didn’t get it to work :-(
Thank you!

**Comment by ServusJon** [comment]
Also is there a way to retrieve the y position of a layer that was set in autolayout respecting the its position in its superview?
I am working on a parallax effect where I want to move views with a factor to their position.

**Comment by nakiostudio** [comment]
Hey @ServusJon 👋 

>Can you please give me an example how I can use the safearealayoutguide on a view?
Didn’t get it to work :-(

Check [this](https://github.com/nakiostudio/EasyPeasy#uilayoutguides).

>Also is there a way to retrieve the y position of a layer that was set in autolayout respecting the its position in its superview?
I am working on a parallax effect where I want to move views with a factor to their position.

`view.frame.origin.y` but you need to take into account that the value changes depending on whether the view and superview have been laid out or not.

**Comment by ServusJon** [comment]
Thanks. With this example at hand I still don’t know how I can use that on my views :-(
Can you please give me a little more details?
