### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by Jur4s** [nakiostudio/EasyPeasy#68]
Xcode 9 doesn't allows Code Coverage into apps : 
```Invalid Bundle - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app.```

--> 
```
"Schemes with Code Coverage enabled (in the Test action) will now always build with Code Coverage, including for the Run and Launch actions. This reduces the need to build multiple versions of the application. Users who require code coverage to be off for their non-test actions can explicitly use a separate scheme with coverage disabled. (31848014)"
```

```Checking ./Carthage/Build/iOS/EasyPeasy.framework/EasyPeasy... LLVM instrumentation symbols found:
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
```

Please deactivate Code Coverage, 

Thx

**Comment by nakiostudio** [comment]
Hi @Jur4s 👋
 
Thanks for reporting. Are you using Carthage to fetch EasyPeasy? I believe this should be sorted out on their end.

**Comment by Jur4s** [comment]
Hi @nakiostudio  👋

Yes I use carthage.
I read some issue about this problem on their GitHub page, apparently, they can't change the "code coverage" settings of the archive scheme so their ask to library's developer to (for now) change it :/ 
A lot of open source library already change it to allows App submission

**Comment by nakiostudio** [comment]
Okay, I will upgrade then 👍

**Comment by Jur4s** [comment]
Thanks you 👍 👍 👍

**Comment by nakiostudio** [comment]
Done :)
