### ISSUE TITLE
Deprecate `<-` Operator

### ISSUE THREAD

**Issue by muukii** [nakiostudio/EasyPeasy#69]
@nakiostudio 

First, Thank you for the very helpful library.
I use always this library in creating applications.

I think we should remove `<-` operator from EasyPeasy.
Instead, we need to add readable function.

Because sometimes operator confuses some developers.
And the operator can be added each project.
I think EasyPeasy should provide layout functions as only functions.

What do you think?
If you like this proposal, I would like to think about the name of the function with you.

**Comment by nakiostudio** [comment]
Hey @muukii.

I'm glad you ask as I was planning to replace it with something similar to the following:

```swift

// Item is the UIView/NSView alias
extension Item {
  func layout(_ attributes: () -> [Attribute]) -> [NSLayoutConstraint]
  func layout(_ attributes: () -> Attribute) -> [NSLayoutConstraint]
}

```

This would change the usage to:

```swift
view.layout {[
    Width(100), 
    Height(58)
]}

view.layout {
    Width(100)
}
```

What do you think?

**Comment by muukii** [comment]
@nakiostudio 

> I was planning
Wow, It's good.

Looks good to me that's syntax.

Another way,

```
func layout(_ attributes: () -> Attribute...) -> [NSLayoutConstraint]
```

```
 view.layout(
    Width(),
    Height(),
    Top()
 )
```

But, We need to care that last element does not have ',' in we are coding.

**Comment by nakiostudio** [comment]
Love your approach, I will draft a PR for that today. Hope we will get feedback from other users too!

**Comment by muukii** [comment]
And, We need to consider the name of the function.

Is keyword `layout`?
Next, does `layout` need prefix?

`layout`
`setLayout`
`addLayout`

**Comment by muukii** [comment]
I think `layout` does not have any problem.
I'm looking forward to your PR!

**Comment by nakiostudio** [comment]
Now that I think about it all the methods extending UIView/NSView are prefixed by `easy_`. Should we go for `easy_layout` instead?

**Comment by nakiostudio** [comment]
Another options is follow the approach used by Kingfisher and other libraries and have a struct in those classes acting as namespace for the library methods, this way we would have:

```swift
view.easy.layout(Size(50))
view.easy.reload()
view.easy.clear()
```

**Comment by muukii** [comment]
@nakiostudio 

That's very good idea.
I like namespace that like `.rx.` and `.kf`.
So, I'm guessing both of `ep` and `easy`.

**Comment by nakiostudio** [comment]
`1.6.0` is out with these changes. Hope people like it :)

Thanks @muukii 🙌
