### ISSUE TITLE
Missing support: UILayoutGuide

### ISSUE THREAD

**Issue by DevAndArtist** [nakiostudio/EasyPeasy#8]
Interesting work. One thing I missed here is support for [`UILayoutGuide's` ](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UILayoutGuide_Class_Reference/index.html#//apple_ref/occ/cl/UILayoutGuide)

 I also like to build AutoLayout frameworks for my project. Maybe I'll use this for some inspirations. 😄

**Comment by nakiostudio** [comment]
Hi @DevAndArtist 👋 Indeed, this feature is in progress therefore it should get merged soon. Glad you've found some inspirations here :)

**Comment by nakiostudio** [comment]
@DevAndArtist done :)

https://github.com/nakiostudio/EasyPeasy/pull/14
