### ISSUE TITLE
Apply safearea to view

### ISSUE THREAD

**Issue by ServusJon** [nakiostudio/EasyPeasy#81]
How can I apply a safearea to a view?

**Comment by fbarraganef** [comment]
I have the same question....

**Comment by nakiostudio** [comment]
Hey! sorry for the late response. Hope the following example helps.

```swift
self.toolbar.easy.layout(
    Top(0.0).to(self.safeAreaLayoutGuide, .top),
    Left(0.0), 
    Right(0.0),
    Height(30.0)
)
```

**Comment by ServusJon** [comment]
Didn’t work for me :-(

**Comment by ServusJon** [comment]
<img width="716" alt="bildschirmfoto 2018-07-09 um 20 33 56" src="https://user-images.githubusercontent.com/783416/42469286-8d4a1fb6-83b7-11e8-9728-90f333271025.png">

**Comment by oneeypi** [comment]
Try:
` Top(0.0).to(view.safeAreaLayoutGuide, .top)`

**Comment by icanswiftabit** [comment]
Shouldn't this be a part of 'BottomMargin()'?
