### ISSUE TITLE
Carthage Support.

### ISSUE THREAD

**Issue by SebastianBO** [nakiostudio/EasyPeasy#9]
Would be lovely, thanks for EasyPeasy!
Great name & structure.

**Comment by nakiostudio** [comment]
Hi @SebastianBO 👋 

Thanks for the request, my colleague @khose will take care of this :)

**Comment by khose** [comment]
Hi @SebastianBO . EasyPeasy is Carthage compatible, although the README wasn't showing that information. Have you tried the normal steps to include it as a dependency in your project? I've tried that and it just works.

Please, let me know if you are getting any specific error so I can dig into it.

Thanks!

**Comment by nakiostudio** [comment]
Just merged the PR with the README update made by @khose 🎉
